// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace CadastroDeUsuarios.API.Models
{
    public partial class CadastroDeUsuariosContext : DbContext
    {
        public CadastroDeUsuariosContext()
        {
        }

        public CadastroDeUsuariosContext(DbContextOptions<CadastroDeUsuariosContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Escolaridade> Escolaridade { get; set; }
        public virtual DbSet<HistoricoEscolar> HistoricoEscolar { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Latin1_General_CI_AS");

            modelBuilder.Entity<Escolaridade>(entity =>
            {
                entity.Property(e => e.Descricao).IsUnicode(false);
            });

            modelBuilder.Entity<HistoricoEscolar>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Descricao).IsUnicode(false);
            });

            modelBuilder.Entity<Usuarios>(entity =>
            {
                entity.Property(e => e.Email).IsUnicode(false);

                entity.Property(e => e.Nome).IsUnicode(false);

                entity.Property(e => e.Sobrenome).IsUnicode(false);

                entity.HasOne(d => d.Escolaridade)
                    .WithMany(p => p.Usuarios)
                    .HasForeignKey(d => d.EscolaridadeId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Usuarios_Escolaridade")
                    ;
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    }
}