// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CadastroDeUsuarios.API.Models
{
    public partial class HistoricoEscolar
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Descricao { get; set; }
    }
}