// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CadastroDeUsuarios.API.Validadores;
using Microsoft.EntityFrameworkCore;

namespace CadastroDeUsuarios.API.Models
{
    public partial class Usuarios
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        [MinLength(3, ErrorMessage = "Nome inválido, informe no mínimo 3 caracteres")]
        [MaxLength(50, ErrorMessage = "Nome excedeu o tamanho permitido")]
        public string Nome { get; set; }

        [Required]
        [StringLength(50)]
        [MinLength(3, ErrorMessage = "Sobrenome inválido, informe no mínimo 3 caracteres")]
        [MaxLength(50, ErrorMessage = "Sobrenome excedeu o tamanho permitido")]
        public string Sobrenome { get; set; }


        [Required]
        [StringLength(50)]
        [EmailAddress(ErrorMessage = "Formato do email inválido")]
        [MaxLength(50, ErrorMessage = "Email excedeu o tamanho permitido")]
        public string Email { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        [Column(TypeName = "date")]
        [DateTimeValidate("DataNascimento")]
        public DateTime DataNascimento { get; set; }

        
        [EscolaridadeValidate("EscolaridadeId")]
        public int EscolaridadeId { get; set; }

        public int? HistoricoEscolarId { get; set; }

        [ForeignKey(nameof(EscolaridadeId))]
        [InverseProperty("Usuarios")]
        
        public virtual Escolaridade Escolaridade { get; set; }
        
    }
}